---
kind: Service
apiVersion: v1
metadata:
  name: exampleservice
spec:
  selector:
    app: badrawiserver
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8081
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30002
  type: LoadBalancer
 
 
 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: badrawideployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: badrawiserver
    spec:
      containers:
        - name: badrawiserver
          image: badrawi/n-odata-server
          ports:
            - containerPort: 80